HANDLE_COMMAND(HLT)

HANDLE_COMMAND(PUSH)
HANDLE_COMMAND(PUSHR)
HANDLE_COMMAND(POP)
HANDLE_COMMAND(POPR)

HANDLE_COMMAND(ADD)
HANDLE_COMMAND(SUB)
HANDLE_COMMAND(MLT)
HANDLE_COMMAND(DIV)

HANDLE_COMMAND(SQRT)
HANDLE_COMMAND(POW)

HANDLE_COMMAND(IN)
HANDLE_COMMAND(OUT)

HANDLE_COMMAND(JMP)
HANDLE_COMMAND(JB)
HANDLE_COMMAND(JBE)
HANDLE_COMMAND(JA)
HANDLE_COMMAND(JAE)
HANDLE_COMMAND(JE)
HANDLE_COMMAND(JNE)

HANDLE_COMMAND(CALL)
HANDLE_COMMAND(RET)

HANDLE_COMMAND(PUSHM)
HANDLE_COMMAND(POPM)

HANDLE_COMMAND(DRAW)
